spring.application.name=demo3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.datasource.url=jdbc:sqlserver://fa25-capstone.database.windows.net:1433;database=Capstone;user=capstoneUser@fa25-capstone;password=capUser1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB